### ISSUE TITLE
Epic: Race Sessions

### ISSUE THREAD

**Issue by felixssimoes** [felixssimoes/SimChamp#26]
### Actions
- List race sessions
- Add session to race
- Edit race session
- Delete session (only before the race event starts)
- Cancel session

### Model
- Start date & time
- Duration type (time, laps or both)
- Duration time
- Duration laps

### User Stories
- [ ] As a user I want to be able to see one race sessions
- [ ] As a championship admin I want to be able to add sessions to one race *
- [ ] As a championship admin I want to be able to edit a race session *
- [ ] As a championship admin I want to be able to delete a race session *
- [ ] As a championship admin I want to be able to cancel a session *

_* Action only valid for championships where user is the admin._
