### ISSUE TITLE
Epic: Protests

### ISSUE THREAD

**Issue by felixssimoes** [felixssimoes/SimChamp#27]
- [ ] As a driver I want to be able to file a protest against other driver
- [ ] As a driver I want to be able to see all my protests for a race
- [ ] As a driver I want to be able to remove/cancel one protest.
 - Only if it's not yet analysed by the championship admin.
- [ ] As a user I want to see all my protest filed in all races I took part.
- [ ] As a championship admin I want to be able to see all protests for one race
- [ ] As a championship admin I want to be able to filter on race's protests by it's status
- [ ] As a championship admin I want to be able to able to change one protest status.
 - Only to Penalty Applied or Overruled)
- [ ] As a championship admin I want to be able to reply to a protest.

### Model
- Status (Pending; Canceled; Penalty Applied; Overruled)
- Driver
- Description of the protested occurrence.
#### Rleatioships
- Is part of one Race #4 
- [ ] Penalty Applied
