### ISSUE TITLE
Epic: Penalties

### ISSUE THREAD

**Issue by felixssimoes** [felixssimoes/SimChamp#28]
### User Stories
- [ ] As a championship admin I want to be able to apply penalties to one or more race's drivers
- [ ] As a championship admin I want to be able to remove penalties to one race's drivers
- [ ] As a driver I want to be able to see my race's penalties
- [ ] As a user I want to be able to see all my penalties of all the races I took part
- [ ] As a user I want to be able to filter my penalties by:
 - Championship
 - Race

### Model
- Type (Time, Points, Position)
- Time Value
- Points Value
- Position Value
- Report

#### Relationships
- Is part of one Race #4 
- Is part of one Driver ( Race entry on Races #4 )
